apps/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.HomePageView.as_view()),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("feed/", views.PostListView.as_view(), name="feed"),
    path("post_detail/<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("create/", views.PostCreateView.as_view(), name="post_creation"),
]

apps/shop/urls.py
from django.urls import path
from apps.shop import views

app_name = "shop"
urlpatterns = [
    path("catalog/", view=views.CatalogListView.as_view(), name="catalog"),
    path(
        "category-children/<slug:category_slug>/",
        view=views.CategoryChildrenListView.as_view(),
        name="category-children",
    ),
    path("category-products/<slug:category_slug>/", view=views.ProductsListView.as_view(), name="products"),
    path("cart/", view=views.CartDetailView.as_view(), name="cart"),
    path("add-to-cart/", view=views.UpdateCartView.as_view(), name="add-to-cart"),
    path(
        "get-user-card-product-quantity/<slug:slug>/",
        view=views.GetUserCartProductQuantityView.as_view(),
        name="get-user-card-product-quantity",
    ),
    path("checkout/", view=views.CheckoutView.as_view(), name="checkout"),
    path("order-list/", view=views.OrderListView.as_view(), name="order-list"),
    path("order-management/", view=views.OrderListView.as_view(), name="order-management"),
]

apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = "users"
urlpatterns = [
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path("", RedirectView.as_view(url="blog/", permanent=True), name="home"),
    path("admin/", admin.site.urls, name="index-admin"),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
    path("shop/", include("apps.shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_core/base.html
{% load static %}
<html lang="ru">
    <head>
        <meta name="description"
              content="Псковский блог студентов ИИН">
        <meta name="keywords"
              content="blog, students, programming">
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1">
        <link rel="preconnect"
              href="https://fonts.googleapis.com"
              crossorigin="anonymous">
        <link rel="preconnect"
              href="https://fonts.gstatic.com"
              crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100&display=swap"
              rel="stylesheet"
              crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous"></script>
        <link rel="stylesheet"
              type="text/css"
              href="{% static '_core/css/base.css' %}">
        <title>pesb</title>
    </head>
    <body>
        <div class="Wrapper">
            <!-- Header -->
            <nav class="Navbar navbar navbar-expand-lg">
                <div class="container-fluid justify-content-between">
                    <div class="bs-LogoDiv_Header"
                         href="#">
                        <a href="{% url 'home' %}">
                            <img class="bs-LogoImg"
                                 src="{% static '_core/images/icons/logo_trans.png' %}"
                                 alt="">
                        </a>
                    </div>
                    <button class="navbar-toggler HamburgerButton"
                            type="button"
                            data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasNavbar"
                            aria-controls="offcanvasNavbar">
                        <img class="HamburgerImg"
                             src="{% static '_core/images/icons/hamburger.png' %}"
                             alt="">
                    </button>
                    <div class="SidebarDiv offcanvas offcanvas-end"
                         tabindex="-1"
                         id="offcanvasNavbar"
                         aria-labelledby="offcanvasNavbarLabel">
                        <div class="SidebarHeaderDiv offcanvas-header">
                            <h5 class="offcanvas-title"
                                id="offcanvasNavbarLabel">Меню</h5>
                            <button type="button"
                                    class="btn-close text-reset"
                                    data-bs-dismiss="offcanvas"
                                    aria-label="Close"></button>
                        </div>
                        <div class="SidebarBodyDiv offcanvas-body justify-content-center">
                            <div class="ListDiv_Header">
                                <ul class="bgc-black NavbarUl navbar-nav justify-content-center flex-grow-1 p-0 m-0">
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="{% url 'home' %}">Главная</a>
                                    </li>
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="{% url 'blog:feed' %}">Новости</a>
                                    </li>
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="#">Аккаунт</a>
                                    </li>
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="{% url 'blog:contacts' %}">Связь</a>
                                    </li>
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="{% url 'blog:about' %}">О нас</a>
                                    </li>
                                    <li class="NavItemLi nav-item">
                                        <a class="NavLink nav-link"
                                           href="{% url 'shop:catalog' %}">Каталог</a>
                                    </li>
                                    {% if user.is_authenticated and not user.is_superuser and not user.is_stuff %}
                                        <li class="NavItemLi nav-item">
                                            <a class="NavLink nav-link"
                                               href="{% url 'shop:cart' %}">Корзина</a>
                                        </li>
                                        <li class="NavItemLi nav-item">
                                            <a class="NavLink nav-link"
                                               href="{% url 'shop:order-list' %}">Мои заказы</a>
                                        </li>
                                    {% endif %}
                                    {% if user.is_stuff or user.is_superuser %}
                                        <li class="NavItemLi nav-item">
                                            <a class="NavLink nav-link"
                                               href="{% url 'shop:order-management' %}">Заказы</a>
                                        </li>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                        <li class="nav-item NavItemLi">
                                            <form class="m-0 d-flex"
                                                  action="{% url 'users:logout' %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input type="submit"
                                                       class="NavLink nav-link NavItemLi logout-SubmitButton"
                                                       value="Выйти">
                                            </li>
                                        </form>
                                    {% else %}
                                        <li class="NavItemLi nav-item">
                                            <a class="NavLink nav-link"
                                               href="{% url 'users:login' %}">Войти</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="Content">
                {% block content %}
                {% endblock content %}
            </div>
            <!-- Footer -->
            <footer class="Footer">
                <div class="FooterDiv container-fluid">
                    <div class="CopyrightDiv">
                        <p class="CopyrightP">Copyright 2023 All Rights Reserved PESB</p>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>