apps/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.HomePageView.as_view()),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("feed/", views.PostListView.as_view(), name="feed"),
    path("post_detail/<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("create/", views.PostCreateView.as_view(), name="post_creation"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path("", RedirectView.as_view(url="blog/", permanent=True), name="home"),
    path("admin/", admin.site.urls, name="index-admin"),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
    path("shop/", include("apps.shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from apps.users.models import User
from utils.models import SlugModel


class Post(SlugModel):
    field_to_slug = "title"

    author = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name="blog_posts",
    )
    title = models.CharField(_("Title"), max_length=100)
    content = models.TextField(
        _("Content"),
        max_length=1500,
    )
    summary = models.CharField(_("Summary"), max_length=200)
    created = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)
    updated = models.DateTimeField(_("Updated"), auto_now=True, editable=False)

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")
        ordering = ["-created"]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return reverse("blog:post_detail", kwargs={"slug": str(self.slug)})

apps/blog/forms.py
from django import forms
from . import models


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ["title", "summary", "content"]

apps/blog/views.py
from django.views import generic
from . import models
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin


class HomePageView(generic.TemplateView):
    template_name = "blog/home.html"


class ContactsPageView(generic.TemplateView):
    template_name = "blog/contacts.html"


class AboutPageView(generic.TemplateView):
    template_name = "blog/about.html"


class PostListView(generic.ListView):
    model = models.Post
    template_name = "blog/blog.html"


class PostDetailView(generic.DetailView):
    model = models.Post
    template_name = "blog/post_detail.html"


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "blog/post_creation.html"
    form_class = forms.PostCreationForm
    model = models.Post

    def form_valid(self, form):
        if form.is_valid():
            form.instance.author = self.request.user
            return super().form_valid(form)
        else:
            return super().form_invalid(form)

templates/blog/about.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/about.css' %}">
    <div class="Wrapper">
        <div class="row about-Wrapper_White p-2">
            <div class="col-xs-12 col-sm-4">
                <div class="about-ImageDiv">
                    <img class="about-Image"
                         src="{% static 'blog/images/about/man.png' %}"
                         alt="">
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 d-flex align-items-center">
                <div class="about-TextDiv-pdr">
                    <h1 class="pb-1">Публикуйся</h1>
                    <p>Здесь ты можешь публиковать свои статьи и открытия. Не стесняйся делиться знаниями!</p>
                </div>
            </div>
        </div>
        <div class="row about-Wrapper_Blue justify-content-center p-2">
            <div class="col-xs-12 col-sm-8 d-flex align-items-center">
                <div class="about-TextDiv-pdl">
                    <h1 class="pb-1">Гордись</h1>
                    <p>Дай знать всем чего ты достиг в своей сфере! Напиши пост о своих последних достижениях, и все узнают об этом.</p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-4">
                <div class="about-ImageDiv">
                    <img class="about-Image"
                         src="{% static 'blog/images/about/woman.png' %}"
                         alt="">
                </div>
            </div>
        </div>
        <div class="row about-Wrapper_Red p-2">
            <div class="col-xs-12 col-sm-4">
                <div class="about-ImageDiv">
                    <img class="about-Image"
                         src="{% static 'blog/images/about/people.png' %}"
                         alt="">
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 d-flex align-items-center">
                <div class="about-TextDiv-pdr">
                    <h1 class="pb-1">Общайся</h1>
                    <p>
                        Оставляй комментарии, делись опытом и впечатлениями. Наша цель - создать место, где студенты смогу делиться своими открытиями и достижениями, улучшая знания друг друга.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/blog.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
            integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D"
            crossorigin="anonymous"
            async></script>
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/blog.css' %}">
    <div class="Wrapper blog-Wrapper">
        <div class="row p-5 blog-Info">
            <div class="col-lg-4 col-sm-6 text-center">
                <div class="blog-InfoImageDiv">
                    <img class="blog-InfoImage"
                         src="{% static '_core/images/landing_images/blog_info.png' %}"
                         alt="">
                </div>
            </div>
            <div class="col-lg-8 col-sm-6 align-self-center">
                <div class="blog-InfoTextDiv">
                    <p>
                        Здесь ты можешь найти самые свежие публикации от студентов ПсковГУ!
                        Нажми на карточку чтобы открыть полное содержание поста или
                        на кнопку чтобы написать свой пост!
                    </p>
                    <div>
                        <a class="btn btn-primary create_post-Button"
                           href="{% url 'blog:post_creation' %}">Создать</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row"
             data-masonry='{"percentPosition": true }'>
            {% for post in post_list %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="card m-2 post-Div">
                        <a class="post-Link" href={{ post.get_absolute_url }}></a>
                        <img src=""
                             class="card-img-top"
                             alt="">
                        <div class="card-body">
                            <h5 class="card-title fw-bolder">{{ post.title }}</h5>
                            <p class="card-text post-Summary">{{ post.summary }}</p>
                        </div>
                        <div class="card-footer post-Footer d-flex justify-content-between">
                            <small>{{ post.updated|date:"M d, Y" }}</small>
                            <small>{{ post.author }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/blog/contacts.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/contacts.css' %}">
    <div id="contacts-Wrapper"
         class="contacts-Wrapper Wrapper">
        <div class="row p-2">
            <div class="col-xs-12 d-flex flex-column justify-content-center align-items-center">
                <div class="contacts-TextDiv d-flex flex-column align-items-center">
                    <h1 class="pb-1">Свяжитесь с нами!</h1>
                    <p class="contacts-TextParagraph ta-center">
                        По этим контактам вы можете связаться с нами. Пишите по всем интересующим вопросам.
                    </p>
                </div>
            </div>
        </div>
        <div class="row pb-1">
            <div class="col-xs-12 col-md-6 d-flex flex-column align-items-center pb-2">
                <h3 class="fw-bold text-center">Менеджер</h3>
                <ul class="ContactsUl p-0 m-0">
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/telephone.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">+7-996-947-35-85</p>
                    </li>
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/envelope.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">njt55cs@gmail.com</p>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-md-6 d-flex flex-column align-items-center">
                <h3 class="fw-bold text-center">Команда разработки</h3>
                <ul class="ContactsUl p-0 m-0">
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/telephone.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">+7-996-947-35-85</p>
                    </li>
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/envelope.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">njt55cs@gmail.com</p>
                    </li>
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/github.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">
                            <a href="https://github.com/nylinary"
                               target="_blank">GitHub</a>
                        </p>
                    </li>
                    <li class="contacts-ListItem">
                        <i>
                            <img class="bs-IconImg IconImg" src="{% static "_core/images/icons/telegram.svg" %}" alt="">
                        </i>
                        <p class="bs-IconP IconP">
                            <a href="https://t.me/nylinary"
                               target="_blank">Telegram</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/home.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/home.css' %}">
    <div id="mn-Wrapper"
         class="mn-Wrapper Wrapper">
        <div class="row justify-content-between mn-Wrapper_Content p-2">
            <div class="col-xs-12 col-sm-4 m-auto">
                <div class="mn-ImageDiv">
                    <img class="mn-Image"
                         src="{% static 'blog/images/home/character.png' %}"
                         alt="">
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 d-flex align-items-center">
                <div class="mn-TextDiv">
                    <h1 class="mn-Header ta-center mb-1">Добро пожаловать!</h1>
                    <p>
                        Присоединяйся к нашему студенческому блогу, где мы публикуем свои статьи, рассказываем о личных проектах и достижениях или просто делимся знаниями!
                    </p>
                    <form class="mn-Form BasicForm"
                          method="get"
                          action="{% url 'blog:feed' %}">
                        <input class="mn-SubmitButton SubmitButton"
                               type="submit"
                               value="Начать">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_creation.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/post_creation.css' %}">
    <div class="post-Wrapper Wrapper">
        <div class="row login-Wrapper_Form p-2">
            <div class="col-sm-12">
                <div class="post_creation-FormDiv d-flex flex-column align-items-center justify-content-center">
                    <form class="BasicForm"
                          enctype="multipart/form-data"
                          method="post"
                          action="">
                        {% csrf_token %}
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% for field in form.visible_fields %}
                            {% with label_id=field.id_for_label %}
                                <p class="FieldDiv mb-3">
                                    <label for={{ field.id_for_label }}>
                                        {{ field.label }}:
                                    </label>
                                    {% if label_id == "id_title" %}
                                        {{ field|add_class:"post-TitleInput TextInput pl-1" }}
                                    {% elif label_id == "id_summary" %}
                                        {{ field|add_class:"post-SummaryInput TextInput pl-1" }}
                                    {% elif label_id == "id_content" %}
                                        {{ field|add_class:"post-ContentInput TextInput pl-1" }}
                                    {% endif %}
                                </p>
                                {% if field.errors %}<div class="FormErrors p-0 m-0">{{ field.errors }}</div>{% endif %}
                            {% endwith %}
                        {% endfor %}
                        <input class="SubmitButton post_creation-SubmitButton"
                               type="submit"
                               value="Сохранить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_detail.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'blog/css/post.css' %}">
    <div class="post-Wrapper Wrapper">
        <div class="row">
            <div class="col d-flex justify-content-center">
                <div class="post-Div p-3">
                    <h1 class="post-Header pb-2">{{ post.title }}</h1>
                    <p>{{ post.content }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}