apps/shop/urls.py
from django.urls import path
from apps.shop import views

app_name = "shop"
urlpatterns = [
    path("catalog/", view=views.CatalogListView.as_view(), name="catalog"),
    path(
        "category-children/<slug:category_slug>/",
        view=views.CategoryChildrenListView.as_view(),
        name="category-children",
    ),
    path("category-products/<slug:category_slug>/", view=views.ProductsListView.as_view(), name="products"),
    path("cart/", view=views.CartDetailView.as_view(), name="cart"),
    path("add-to-cart/", view=views.UpdateCartView.as_view(), name="add-to-cart"),
    path(
        "get-user-card-product-quantity/<slug:slug>/",
        view=views.GetUserCartProductQuantityView.as_view(),
        name="get-user-card-product-quantity",
    ),
    path("checkout/", view=views.CheckoutView.as_view(), name="checkout"),
    path("order-list/", view=views.OrderListView.as_view(), name="order-list"),
    path("order-management/", view=views.OrderListView.as_view(), name="order-management"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path("", RedirectView.as_view(url="blog/", permanent=True), name="home"),
    path("admin/", admin.site.urls, name="index-admin"),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
    path("shop/", include("apps.shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from utils.models import SlugModel
from django.core.validators import MinValueValidator


class Product(SlugModel):
    field_to_slug = "name"

    name = models.CharField(_("Name"), max_length=155)
    description = models.TextField(_("Content"), max_length=1500)
    category = models.ForeignKey("ProductCategory", on_delete=models.CASCADE)
    price = models.DecimalField(_("Price"), max_digits=9, decimal_places=2, validators=[MinValueValidator(0)])
    image = models.ImageField(_("Image"), upload_to="products", null=True, blank=True)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    def clean(self) -> None:
        if self.category and self.category.children.exists():
            raise ValidationError("Can not add products to Category with child Category")

    def __str__(self) -> str:
        return self.name


class ProductCategory(SlugModel):
    field_to_slug = "name"

    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="children", verbose_name=_("Parent"), null=True, blank=True
    )
    name = models.CharField(_("Name"), max_length=155)
    description = models.TextField(_("Content"), max_length=1500)
    image = models.ImageField(_("Image"), upload_to="products_categories", null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    def get_children_url(self) -> str:
        return reverse("shop:category-children", kwargs={"category_slug": str(self.slug)})

    def get_products_url(self) -> str:
        return reverse("shop:products", kwargs={"category_slug": str(self.slug)})


class Cart(models.Model):
    user = models.OneToOneField("users.User", on_delete=models.CASCADE, related_name="cart")
    products = models.ManyToManyField(Product, related_name="carts", through="CartProducts")

    def __str__(self) -> str:
        return f"Корзина клиента {self.user.username}"


class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, models.CASCADE, verbose_name=_("Cart"))
    product = models.OneToOneField(
        Product,
        models.CASCADE,
        verbose_name=_("Product"),
    )
    quantity = models.IntegerField(_("Quantity"), default=0, validators=[MinValueValidator(0)])

    def __str__(self) -> str:
        return self.cart.user.username


class Order(models.Model):
    user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="orders")
    products = models.ManyToManyField(Product, related_name="orders", through="OrderProducts")

    def __str__(self) -> str:
        return f"Заказ клиента {self.user.username} №{self.id}"


class OrderProducts(models.Model):
    order = models.ForeignKey(Order, models.CASCADE, verbose_name=_("Order"))
    product = models.ForeignKey(
        Product,
        models.CASCADE,
        verbose_name=_("Product"),
    )
    quantity = models.IntegerField(_("Quantity"), default=0, validators=[MinValueValidator(0)])

    def __str__(self) -> str:
        return self.order.user.username

apps/shop/views.py
import json
from typing import Any, Dict

from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from apps.shop import models
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin


class CatalogListView(generic.ListView):
    context_object_name = "product_category_list"
    queryset = models.ProductCategory.objects.filter(parent__isnull=True)
    template_name = "shop/catalog.html"


class CategoryChildrenListView(generic.ListView):
    context_object_name = "product_category_list"
    model = models.ProductCategory
    template_name = "shop/catalog.html"

    def get_queryset(self) -> QuerySet[Any]:
        return self.model.objects.get(slug=self.kwargs.get("category_slug")).children.all()


class ProductsListView(generic.ListView):
    context_object_name = "products_list"
    model = models.Product
    template_name = "shop/products.html"

    def get_queryset(self) -> QuerySet[Any]:
        return self.model.objects.filter(category__slug=self.kwargs.get("category_slug"))


class CartDetailView(LoginRequiredMixin, generic.ListView):
    context_object_name = "products_list"
    model: models.Cart = models.Cart
    template_name = "shop/cart.html"

    def get_queryset(self) -> QuerySet[Any]:
        cart, _ = self.model.objects.get_or_create(user=self.request.user)
        return models.CartProducts.objects.filter(cart=cart, quantity__gt=0)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        objects = context[self.context_object_name]
        context["total"] = int(sum(obj.product.price * obj.quantity for obj in objects))

        context[self.context_object_name] = [(obj.product, obj.quantity) for obj in objects]

        return context


class UpdateCartView(LoginRequiredMixin, generic.View):
    def post(self, request: HttpRequest) -> JsonResponse:
        self.request = request
        body = self.get_body()

        cart, _ = models.Cart.objects.get_or_create(user=self.request.user)
        product = models.Product.objects.get(slug=body["slug"])
        cart_product, _ = models.CartProducts.objects.get_or_create(cart=cart, product=product)

        quantity = cart_product.quantity + body.get("quantity", 0)

        cart_product.quantity = quantity if quantity > 0 else 0

        if cart_product.quantity == 0:
            cart_product.delete()
        else:
            cart_product.save()

        return JsonResponse({"status": 200})

    def get_body(self) -> Dict:
        body_unicode = self.request.body.decode("utf-8")
        return json.loads(body_unicode) if body_unicode else {}


class GetUserCartProductQuantityView(LoginRequiredMixin, generic.View):
    def get(self, request: HttpRequest, slug: str) -> JsonResponse:
        product = models.Product.objects.get(slug=slug)
        if card_product := models.CartProducts.objects.filter(
            cart=models.Cart.objects.get(user=request.user), product=product
        ).first():
            quantity = card_product.quantity
        else:
            quantity = 0
        return JsonResponse({"quantity": quantity})


class CheckoutView(LoginRequiredMixin, generic.View):
    def get(self, request):
        cart = models.Cart.objects.get(user=request.user)

        if cart.products.all():
            order = models.Order.objects.create(user=request.user)

            for product in cart.products.all():
                quantity = models.CartProducts.objects.get(cart=cart, product=product).quantity
                models.OrderProducts.objects.create(order=order, product=product, quantity=quantity)

            models.CartProducts.objects.filter(cart=cart).delete()

        return HttpResponseRedirect(reverse("shop:order-list"))


class OrderListView(LoginRequiredMixin, generic.ListView):
    context_object_name = "orders_list"
    model: models.Order = models.Order
    template_name = "shop/orders.html"

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.user.is_staff or self.request.user.is_superuser:
            self.template_name = "shop/orders_management.html"
            return self.model.objects.all()
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context[self.context_object_name] = [
            (obj, self.get_order_summary(obj)) for obj in context[self.context_object_name]
        ]
        return context

    def get_order_summary(self, order: models.Order) -> str:
        order_products = models.OrderProducts.objects.filter(order=order)

        return (f"{product.product.name} * {product.quantity}" for product in order_products)

templates/shop/cart.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'shop/css/cart.css' %}">
    <script src="{% static 'shop/js/cart.js' %}"
            type="module"></script>
    <div class="Wrapper products-Wrapper">
        <div class="row"
             data-masonry='{"percentPosition": true }'>
            <div class="row g-0">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="d-flex justify-content-between align-items-center mb-5">
                            <h1 class="fw-bold mb-0 text-black">Корзина</h1>
                            <h6 class="mb-0 text-muted">{{ products_list.count }} покупки</h6>
                        </div>
                        <hr class="my-4">
                        {% for product, quantity in products_list %}
                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                    <img src={{ product.image.url }} class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-3">
                                    <h6 class="text-muted">{{ product.name }}</h6>
                                    <h6 class="text-black mb-0">{{ product.description }}</h6>
                                </div>
                                <div class="col-md-5 col-lg-4 col-xl-4 d-flex">
                                    <div class="quantity d-flex flex-row">
                                        {% comment %} <button class="minus products-SubmitButton SubmitButton"
         aria-label="Decrease">&minus;</button> {% endcomment %}
                                        <p class="product-quantity ps-2 pe-2">{{ quantity }}</p>
                                        <p class="product-info"
                                           price="{{ product.price }}"
                                           quantity="{{ quantity }}"
                                           slug="{{ product.slug }}"></p>
                                        {% comment %} <button class="plus products-SubmitButton SubmitButton"
         aria-label="Increase">&plus;</button> {% endcomment %}
                                    </div>
                                </div>
                                <div class="col-md-1 col-lg-1 col-xl-1 offset-lg-1">
                                    <h6 class="mb-0">{{ product.price }} RUB</h6>
                                </div>
                            </div>
                            <hr class="my-4">
                        {% endfor %}
                        <div class="pt-5">
                            <h6 class="mb-0">
                                <a href="{% url 'shop:catalog' %}"
                                   class="text-body">В каталог</a>
                            </h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="p-5">
                        <h3 class="fw-bold mb-5 mt-2 pt-1">Заказ</h3>
                        <hr class="my-4">
                        <h5 class="text-uppercase mb-3">Промокод</h5>
                        <div class="mb-5">
                            <div data-mdb-input-init
                                 class="form-outline">
                                <input type="text"
                                       id="checkoutForm"
                                       class="form-control form-control-md" />
                            </div>
                        </div>
                        <hr class="my-4">
                        <div class="d-flex justify-content-between mb-5">
                            <h5 class="text-uppercase">Всего</h5>
                            <h5 id="total">{{ total }}</h5>
                            <h5>RUB</h5>
                        </div>
                        <form class="mn-Form BasicForm"
                              method="get"
                              action="{% url 'shop:checkout' %}">
                            <input class="mn-SubmitButton SubmitButton"
                                   type="submit"
                                   value="Оформить заказ">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/shop/catalog.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'shop/css/catalog.css' %}">
    <div class="Wrapper catalog-Wrapper">
        <div class="row justify-content-center">
            {% for category in product_category_list %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="card m-2 category-Div h-100">
                        {% if category.children.all %}
                            <a class="category-Link" href={{ category.get_children_url }}></a>
                        {% else %}
                            <a class="category-Link" href={{ category.get_products_url }}></a>
                        {% endif %}
                        <img src={{ category.image.url }} class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-name fw-bolder">{{ category.name }}</h5>
                            <p class="card-text category-Description">{{ category.description }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/shop/orders.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'shop/css/orders.css' %}">
    <div class="Wrapper catalog-Wrapper">
        <div class="row justify-content-center">
            {% for order, description in orders_list %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="card m-2 category-Div h-100">
                        <div class="card-header">
                            <h5 class="card-name fw-bolder">Заказ №{{ order.id }}</h5>
                        </div>
                        <div class="card-body">
                            {% for pd in description %}<p class="m-0">{{ pd }}</p>{% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/shop/orders_management.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'shop/css/orders-management.css' %}">
    <div class="Wrapper catalog-Wrapper">
        <div class="row justify-content-center">
            {% for order, description in orders_list %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="card m-2 category-Div h-100">
                        <div class="card-header">
                            <h5 class="card-name fw-bolder">Заказ №{{ order.id }} пользователя {{ order.user }}</h5>
                        </div>
                        <div class="card-body">
                            {% for pd in description %}<p class="m-0">{{ pd }}</p>{% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/shop/products.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'shop/css/products.css' %}">
    <script src="{% static 'shop/js/products.js' %}"
            type="module"></script>
    <div class="Wrapper products-Wrapper">
        <div class="row justify-content-center">
            {% for product in products_list %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-2">
                    <div class="card m-2 product-Div h-100 product">
                        <img src={{ product.image.url }} class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-name fw-bolder">{{ product.name }}</h5>
                            <p class="card-text product-Description">{{ product.description }}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between flex-column">
                            <p>{{ product.price }}</p>
                            <div hidden
                                 class="quantity">
                                {% comment %} <button class="minus products-SubmitButton SubmitButton" aria-label="Decrease">&minus;</button> {% endcomment %}
                                <p class="product-quantity ps-2 pe-2">0</p>
                                {% comment %} <button class="plus products-SubmitButton SubmitButton" aria-label="Increase">&plus;</button> {% endcomment %}
                            </div>
                            <a class="add-to-cart-link" slug={{ product.slug }}>
                                <button class="products-SubmitButton SubmitButton">В корзину</button>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}