apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = "users"
urlpatterns = [
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path("", RedirectView.as_view(url="blog/", permanent=True), name="home"),
    path("admin/", admin.site.urls, name="index-admin"),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
    path("shop/", include("apps.shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.validators import MinLengthValidator


class LowercaseCharField(models.CharField):
    """
    Переопределенный CharField для конвертации строки в нижний
    регистр перед сохранением или получением данных.
    """

    def to_python(self, value):
        """
        Переводит строку в нижний регистр.
        """
        value = super().to_python(value)
        if isinstance(value, str):
            return value.lower()
        return value


class LowercaseEmailField(models.EmailField):
    """
    Переопределенный EmailField для конвертации email в нижний
    регистр перед сохранением или получением данных.
    """

    def to_python(self, value):
        """
        Переводит строку в нижний регистр.
        """
        value = super().to_python(value)
        # Check if value is a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value


class User(AbstractUser):
    username_validator = ASCIIUsernameValidator()
    username = LowercaseCharField(
        _("Username"),
        max_length=36,
        unique=True,
        help_text=_("Required. From 4 to 36 symbols. Only letters, digits and @/./+/-/_"),
        validators=[username_validator, MinLengthValidator(4)],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
        db_index=True,
    )
    first_name = models.CharField(_("First name"), max_length=128, blank=False, db_index=True)
    last_name = models.CharField(_("Last name"), max_length=128, blank=False, db_index=True)
    middle_name = models.CharField(_("Surname"), max_length=128, blank=True, null=True, db_index=True)
    email = LowercaseEmailField(_("Email"), max_length=36, unique=True, blank=False, db_index=True)

    def __str__(self) -> str:
        return self.username

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField, AuthenticationForm
from .models import User
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy as _


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label=_("Username"),
        max_length=36,
        min_length=4,
        validators=[ASCIIUsernameValidator(), MinLengthValidator(4)],
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    email = forms.EmailField(label=_("Email"), widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ("username", "email")
        field_classes = {"username": UsernameField}


class LoginForm(AuthenticationForm):
    """Form for login page."""

apps/users/views.py
from django.views.generic.edit import CreateView
from .forms import RegistrationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView as BaseLoginView


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = "users/registration.html"
    # TODO Redirect to blog list
    success_url = reverse_lazy("blog:feed")


class LoginView(BaseLoginView):
    template_name = "users/login.html"

templates/users/login.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    {% comment %} Set css classes to django forms auto-generaged fields {% endcomment %}
    {% load widget_tweaks %}
    <link rel="stylesheet"
          href="{% static 'users/css/login.css' %}">
    <div class="Wrapper login-Wrapper">
        <div class="row login-Wrapper_Form p-2">
            <div class="col-sm-12">
                <div class="login-FormDiv d-flex flex-column align-items-center justify-content-center">
                    <h1 class="pb-1">Войти</h1>
                    <p id="WarningMessage"></p>
                    <form class="BasicForm"
                          enctype="multipart/form-data"
                          method="post"
                          action="">
                        {% csrf_token %}
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% for field in form.visible_fields %}
                            {% with label_id=field.id_for_label %}
                                <p class="FieldDiv mt-3 mb-0">
                                    <label for={{ field.id_for_label }}>
                                        {{ field.label }}:
                                    </label>
                                    {% if label_id == "id_username" %}
                                        {{ field|add_class:"UsernameInput TextInput pl-1" }}
                                    {% elif label_id == "id_password" %}
                                        {{ field|add_class:"PasswordInput TextInput pl-1" }}
                                    {% endif %}
                                </p>
                                {% if field.errors %}<div class="FormErrors p-0 m-0">{{ field.errors }}</div>{% endif %}
                            {% endwith %}
                        {% endfor %}
                        <div class="registrationLinkDiv mb-3">
                            <a class="registration-Link"
                               href="{% url 'users:registration' %}">Зарегистрироваться</a>
                        </div>
                        <input class="SubmitButton login-SubmitButton"
                               type="submit"
                               value="Войти">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/registration.html
{% extends "_core/base.html" %}
{% block content %}
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet"
          href="{% static 'users/css/registration.css' %}">
    <div class="Wrapper registration-Wrapper">
        <div class="row registration-Wrapper_Form p-2">
            <div class="col">
                <div class="registration-FormDiv d-flex flex-column align-items-center justify-content-center">
                    <h1 class="pb-1">Регистрация</h1>
                    <p id="WarningMessage"></p>
                    <form class="registration-Form BasicForm"
                          enctype="multipart/form-data"
                          method="post"
                          action="">
                        {% csrf_token %}
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% for field in form.visible_fields %}
                            {% with label_id=field.id_for_label %}
                                <p class="mb-3 FieldDiv">
                                    <label for={{ field.id_for_label }}>
                                        {{ field.label }}:
                                    </label>
                                    {% if label_id == "id_email" %}
                                        {{ field|add_class:"EmailInput TextInput pl-1" }}
                                    {% elif label_id == "id_username" %}
                                        {{ field|add_class:"UsernameInput TextInput pl-1" }}
                                    {% elif label_id == "id_password1" or label_id == "id_password2" %}
                                        {{ field|add_class:"PasswordInput TextInput pl-1" }}
                                    {% else %}
                                        {{ field|add_class:"TextInput pl-1" }}
                                    {% endif %}
                                </p>
                                {% if field.errors %}<div class="FormErrors p-0 m-0">{{ field.errors }}</div>{% endif %}
                            {% endwith %}
                        {% endfor %}
                        <input class="registration-SubmitButton SubmitButton"
                               type="submit"
                               value="Зарегистрироваться">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}